# Generated by Django 3.2 on 2021-05-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='follower', related_query_name='follower', to='user.Profile'),
        ),
    ]
